Added support for multiple file deployment
archethic-foundation/aeweb-cli pull request #28
Opened 2022-02-08 14:38 UTC by manujuniris

2022-02-08 17:53 UTC, samuel-uniris requested changes
Good overall.
The thing is done and worling.

But in addition to the comments, I also think you can leverage async/await to avoid callbacks hell and make code more readable. 
Moreover I will request better error handling to catch the potential failed promises.

2022-02-08 17:53 UTC, samuel-uniris commented on aeweb.js
> +        archethic.sendTransaction(txn, argv.endpoint)
You should wait the completion before to continue further. Othewise the transaction may not be validated yet

2022-02-08 18:37 UTC, redDwarf03 commented
hello 
could explain in the readme.md how to create subfolder please

is it 
aeweb deploy-folder --seed=myseedphrase --endpoint=https://testnet.archethic.net --folder=Aeweb/images ?

2022-02-08 19:42 UTC, redDwarf03 commented
just for info, I tried to publish the wallet with this script and with the content of the zip file

```

aeweb generate-address --seed=archethicWalletTest --index=0

aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/assets
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/assets/buy
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/assets/fonts
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/assets/icons
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/assets/themes
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/fonts
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/packages
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/packages/cupertino_icons
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/packages/cupertino_icons/assets
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/packages/font_awesome_flutter
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/packages/font_awesome_flutter/lib
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=assets/packages/font_awesome_flutter/lib/fonts
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=canvaskit
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=canvaskit/profiling
aeweb deploy-folder --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --folder=icons


aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/favicon.png 
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/flutter_service_worker.js
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/main.dart.js
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/main.dart.js.map
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/manifest.json
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/version.json
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/index.html
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/version.json
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/.last_build_id
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/icons/Icon-192.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/icons/Icon-maskable-192.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/icons/Icon-maskable-512.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/icons/Icon-512.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/AssetManifest.json
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/NOTICES
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/FontManifest.json
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/packages/font_awesome_flutter/lib/fonts/fa-solid-900.ttf
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/packages/font_awesome_flutter/lib/fonts/fa-regular-400.ttf
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/packages/font_awesome_flutter/lib/fonts/fa-brands-400.ttf
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/fonts/MaterialIcons-Regular.otf
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/warning.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/privacyPolicy.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/PreviousSignature.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/Code.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/TimeStamp.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/Type.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/OriginSignature.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/Address.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/ProofOfWork.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/Content.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/ProofOfIntegrity.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/Version.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/PreviousPublicKey.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/Amount.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/To.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/txInfos/Signature.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/authentication.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/autoLock.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/themes.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://testnet.archethic.net --index=0 --path=./web/assets/assets/icons/lock.png
aeweb deploy-file --seed=archethicWalletTest --endpoint=https://test [...]

2022-02-09 20:50 UTC, redDwarf03 commented
hello
I run my script again with your last updates.
i obtain my html page: https://testnet.archethic.net/api/last_transaction/00fb98ea696f2005a2a022a6f95fa20f8d191a055b4bfcd957a2c2635c1c3817f1/content?mime=text/html
The source code is ok but it seems the assets don't work.

i have a question.
when I send for example few images, I have always the same url : 
https://testnet.archethic.net/api/last_transaction/00fb98ea696f2005a2a022a6f95fa20f8d191a055b4bfcd957a2c2635c1c3817f1/content?mime=image/png 

how can I display an image from a website host on archethic blockchain alone in a browser ?

2022-02-10 07:55 UTC, manujuniris commented
> hello I run my script again with your last updates. i obtain my html page: https://testnet.archethic.net/api/last_transaction/00fb98ea696f2005a2a022a6f95fa20f8d191a055b4bfcd957a2c2635c1c3817f1/content?mime=text/html The source code is ok but it seems the assets don't work.
> 
> i have a question. when I send for example few images, I have always the same url : https://testnet.archethic.net/api/last_transaction/00fb98ea696f2005a2a022a6f95fa20f8d191a055b4bfcd957a2c2635c1c3817f1/content?mime=image/png
> 
> how can I display an image from a website host on archethic blockchain alone in a browser ?

Hello
The last update supports single file deployment and multiple files deployment.

At first, run - sudo npm link

To deploy a single file - 
1. Generate address -
aeweb generate-address --seed=myseedphrase --index=0
2. Transfer funds to the generated address using faucet -
https://testnet.archethic.net/faucet
3. Deploy a file -
aeweb deploy-file --seed=myseedphrase --endpoint=https://testnet.archethic.net --file=./image.png

To deploy a folder -
1. Generate address -
aeweb generate-address --seed=myseedphrase --index=0
2. Transfer funds to the generated address using faucet -
https://testnet.archethic.net/faucet
3. Deploy a folder - 
aeweb deploy-folder --seed=myseedphrase --endpoint=https://testnet.archethic.net --folder=Aeweb

Note - 
Here, Aeweb is the name of your folder inside which you may have your files
For multi-files, the transaction hash generated depends on the seed you choose and the filename

2022-02-10 08:01 UTC, redDwarf03 commented
> > hello I run my script again with your last updates. i obtain my html page: https://testnet.archethic.net/api/last_transaction/00fb98ea696f2005a2a022a6f95fa20f8d191a055b4bfcd957a2c2635c1c3817f1/content?mime=text/html The source code is ok but it seems the assets don't work.
> > i have a question. when I send for example few images, I have always the same url : https://testnet.archethic.net/api/last_transaction/00fb98ea696f2005a2a022a6f95fa20f8d191a055b4bfcd957a2c2635c1c3817f1/content?mime=image/png
> > how can I display an image from a website host on archethic blockchain alone in a browser ?
> 
> Hello The last update supports single file deployment and multiple files deployment.
> 
> At first, run - sudo npm link
> 
> To deploy a single file -
> 
> 1. Generate address -
>    aeweb generate-address --seed=myseedphrase --index=0
> 2. Transfer funds to the generated address using faucet -
>    https://testnet.archethic.net/faucet
> 3. Deploy a file -
>    aeweb deploy-file --seed=myseedphrase --endpoint=https://testnet.archethic.net --file=./image.png
> 
> To deploy a folder -
> 
> 1. Generate address -
>    aeweb generate-address --seed=myseedphrase --index=0
> 2. Transfer funds to the generated address using faucet -
>    https://testnet.archethic.net/faucet
> 3. Deploy a folder -
>    aeweb deploy-folder --seed=myseedphrase --endpoint=https://testnet.archethic.net --folder=Aeweb
> 
> Note - Here, Aeweb is the name of your folder inside which you may have your files For multi-files, the transaction hash generated depends on the seed you choose and the filename

and have you fot an example to deploy a subfolder please

2022-02-10 08:14 UTC, manujuniris commented
> > > hello I run my script again with your last updates. i obtain my html page: https://testnet.archethic.net/api/last_transaction/00fb98ea696f2005a2a022a6f95fa20f8d191a055b4bfcd957a2c2635c1c3817f1/content?mime=text/html The source code is ok but it seems the assets don't work.
> > > i have a question. when I send for example few images, I have always the same url : https://testnet.archethic.net/api/last_transaction/00fb98ea696f2005a2a022a6f95fa20f8d191a055b4bfcd957a2c2635c1c3817f1/content?mime=image/png
> > > how can I display an image from a website host on archethic blockchain alone in a browser ?
> > 
> > 
> > Hello The last update supports single file deployment and multiple files deployment.
> > At first, run - sudo npm link
> > To deploy a single file -
> > 
> > 1. Generate address -
> >    aeweb generate-address --seed=myseedphrase --index=0
> > 2. Transfer funds to the generated address using faucet -
> >    https://testnet.archethic.net/faucet
> > 3. Deploy a file -
> >    aeweb deploy-file --seed=myseedphrase --endpoint=https://testnet.archethic.net --file=./image.png
> > 
> > To deploy a folder -
> > 
> > 1. Generate address -
> >    aeweb generate-address --seed=myseedphrase --index=0
> > 2. Transfer funds to the generated address using faucet -
> >    https://testnet.archethic.net/faucet
> > 3. Deploy a folder -
> >    aeweb deploy-folder --seed=myseedphrase --endpoint=https://testnet.archethic.net --folder=Aeweb
> > 
> > Note - Here, Aeweb is the name of your folder inside which you may have your files For multi-files, the transaction hash generated depends on the seed you choose and the filename
> 
> and have you got an example to deploy a subfolder please ?

Yes, files inside the subfolder will also be deployed.
![cli](https://user-images.githubusercontent.com/90322956/153365318-6eccaab2-2a41-4a04-8d73-01040166e2a8.png)

2022-02-14 21:50 UTC, samuel-uniris requested changes

2022-02-14 21:50 UTC, samuel-uniris commented on aeweb.js
> +        const index = await archethic.getTransactionIndex(address, argv.endpoint)
I think this call should be also in the try catch

2022-02-14 21:50 UTC, samuel-uniris commented on aeweb.js
> +            const index = await archethic.getTransactionIndex(address, argv.endpoint)
Same here

2022-02-15 15:25 UTC, samuel-uniris approved these changes

2022-02-15 15:26 UTC, merged