Displaying uco price and prompting user confirmation
archethic-foundation/aeweb-cli pull request #50
Opened 2022-03-28 03:55 UTC by manujuniris

2022-03-28 07:32 UTC, samuel-uniris requested changes
I think you can display the fee and rate in the confirmation .

For example: 
"The transaction would cost X UCO ( $Y). Do you confirm? "

2022-03-28 07:58 UTC, manujuniris commented
> I think you can display the fee and rate in the confirmation .
> 
> For example: "The transaction would cost X UCO ( $Y). Do you confirm? "

Done

2022-03-28 10:31 UTC, blackode requested changes
- [x] Read PR description
- [x] Read AC
- [x] Pulled branch, manually tested, verified AC are met
- [x] Reviewed the code

I feel like evaluating and user input is not performed here...

Please check this.
![image](https://user-images.githubusercontent.com/9107477/160379559-d016e6e6-f4a7-4f40-a4a4-814df21af47c.png)

2022-03-28 10:31 UTC, blackode commented on commands/deploy_folder.js
> +            });
I don't see you are saving the user input here. I mean, If he/she type `yes` or `no`. 
I don't see the logic for yes and no sections here...

If he/she press no means It should not allow transaction right? If yes, then it is not happening.

I feel like we are just prompting the message but not considering the user input any how.

2022-03-28 10:31 UTC, blackode commented on commands/deploy_website.js
> +            });
same here too...

2022-03-28 10:31 UTC, blackode commented on commands/deploy_website.js
> +                });
here as well...

2022-03-28 11:06 UTC, blackode reviewed
![image](https://user-images.githubusercontent.com/9107477/160384930-045a7928-6e91-4c4b-bb22-9d8046bfef28.png)
After the transaction is successful, It is not coming out of the process. Is that Normal ?
I mean It is not allowing me to enter one more command... 

I have to press Ctrl+c then have to submit again.    

Is this expected behavior?

2022-03-28 12:33 UTC, blackode approved these changes
- [x] Read PR description
- [x] Read AC
- [x] Pulled branch, manually tested, verified AC are met
- [x] Reviewed the code
- [x] Deploying File
![image](https://user-images.githubusercontent.com/9107477/160397309-476de66f-67e2-4770-a5b8-c575b9c34191.png)

- [x] Deploying Folder
![image](https://user-images.githubusercontent.com/9107477/160397243-06f977bd-3740-48bc-a6a7-e5d5a86c17f1.png)

- [x] Deploying website

2022-03-28 18:07 UTC, manujuniris commented
> A comment regarding confirmation when we are deploying multiple files. You see the confirmation doesn't give much information about which file the transaction is about. Do you see a way to enhance it, to give more hint for fee and confirmation ?

Fixed by displaying "File deployed successfully", after sending transaction successfully.

2022-03-29 07:39 UTC, samuel-uniris approved these changes

2022-03-29 07:41 UTC, merged